### ISSUE TITLE
Presentation Review

### ISSUE THREAD

**Issue by jshcrowthe** [jshcrowthe/polymer-angularjs#1]
This is a place for recording comments from content reviewal. 
The actual presentation can be viewed at: http://jshcrowthe.github.io/polymer-angularjs/#1

The first code demo I will be showing is here: https://github.com/jshcrowthe/github-user/blob/master/github-user.html (Working demo: http://jshcrowthe.github.io/github-user/)

The second code demo I will be showing is here: https://github.com/jshcrowthe/polymer-angular-demo/blob/master/polymer-events.html#L28-L57 (I will explain this and then show the demo working at: http://jshcrowthe.github.io/polymer-angular-demo/)

Feel free to add comments as you see fit!

**Comment by jshcrowthe** [comment]
@lambertsteven, @redbugz, @spacerockzero @dncrews, @intervalia These are my AngularSummit 2015 presentation slides for the presentation "Angular.js and Polymer WebComponents". If you are willing and have a little extra time to go through these and leave me some feedback that'd be great! The link to the github pages URL is above along with all associated demos.

Thanks so much for your help guys!

**Comment by intervalia** [comment]
Slide 19: you can still have views, limited directives and view models.
You also have a type of services.

**Comment by jshcrowthe** [comment]
Adding @misbach

**Comment by jshcrowthe** [comment]
Add a few slides explaining Web Components

**Comment by lambertsteven** [comment]
When you talk about Developing Custom Web Components starting at slide 25, you might consider talking about the code first (slide 32) before you talk about polyserve and vulcanize. The reason being that both polyserve and vulcanize are not necessary for writing a basic web component. Instead, each is used to address different issues when trying to use those web components in the web or sharing those components. So instead of talking about how polymer solved an architectural problem that they themselves created (polyserve + bower) or how to solve a problem with using lots of web components (vulcanize + http1.1), you might want to focus on web components and how to create them first. Then with an understanding of web components you could talk about what problems they have and how to address them.

**Comment by lambertsteven** [comment]
slide 42 needs a space in the second bullet point between "writeangular"

**Comment by lambertsteven** [comment]
Slide 41 says "To the code (again)", but you don't have a code slide to explain how to use polymer and angular together correctly.

**Comment by jshcrowthe** [comment]
Thanks all for your help on this!
